CB-7004: Uninstall of mobilespec's dependencies plugin fails
It was trying to uninstall BlackBerry specific plugin from Android:
Error: ENOENT, no such file or directory
'.../mobilespec/plugins/com.blackberry.utils/plugin.xml'

This is due to a recent commit
c7f4f7fc1f60357900ecf98a30c0f0969bc07e68

Added a simple check to just return if a the plugin dir exists.